### ISSUE TITLE
Not able to resolve the VPC endpoint of AWS ES service

### ISSUE THREAD

**Issue by kalroy** [nicholaschiasson/ngx_upstream_jdomain#61] opened 2021-02-08 12:59 UTC
Hi,

I have setup Nginx with ngx_upstream_jdomain to point to a VPC endpoint exposed over AWS Elasticsearch Service.

```
  resolver 127.0.0.34;
  
  upstream backend {
    jdomain xx.xx.xx.xx.com port=443 max_ips=1 interval=20 strict;
    keepalive 24;
  }
  
  location / {
     proxy_pass https://backend;
  }
```

But in case I am changing the data nodes of the cluster triggering a blue/green deployment and assigning a new IP address to the VPC endpoint, Nginx is not able to connect to the new endpoint.

I am using:
Nginx - 1.19.2
Jdomain - 1.1.5

**Comment by kalroy** [comment] 2021-02-08 17:36
I tried to debug it using TCPdump and monitoring the UDP traffic at port 53 and I came to the conclusion that DNS resolution request is being done only during the start of the service and not when I am making request calls.

Is there any issue in the configuration above?

**Comment by nicholaschiasson** [comment] 2021-03-04 15:32
Hi @kalroy sorry for the late response. I haven't had much time to support this project.

There does not appear to be any real issue with your config, although I wonder if you really want to be using the `strict` attribute.

The only thing that jumps out at me is the fact that you are using mainline nginx, and I haven't tested the module against it yet, only stable. I will try to make time to look into this.

**Comment by nicholaschiasson** [comment] 2022-06-05 19:41
Hi @kalroy , with the merge of #75 would you be able to validate if this is still an issue? I suspect this is a duplicate of #60 which I believe to be fixed now. I will close this issue for now as well and if you are able disprove it being fixed then please write back here and I'll reopen it. Thanks for raising this and sorry for the long wait.

**Closed by nicholaschiasson** 2022-06-05 19:41 UTC
Labels: bug, help wanted
